"""agrega motivo_fallo a paradas_ruta

Revision ID: 0e909ac798f2
Revises: f716e6721aa3
Create Date: 2026-09-30 11:17:14.302844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e909ac798f2'
down_revision: Union[str, Sequence[str], None] = 'f716e6721aa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paradas_ruta', sa.Column('motivo_fallo', sa.Enum('CLIENTE_AUSENTE', 'RECHAZO_ENTREGA', 'DIRECCION_INCORRECTA', 'MERCADERIA_DANADA', 'PROBLEMA_VEHICULO', 'OTRO', name='motivo_fallo', native_enum=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paradas_ruta', 'motivo_fallo')
    # ### end Alembic commands ###
