"""entregas pendientes con duenio empresa o chofer

Revision ID: 3f00b225523a
Revises: eb99de48cd4e
Create Date: 2026-10-06 19:33:02.840331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f00b225523a'
down_revision: Union[str, Sequence[str], None] = 'eb99de48cd4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entregas_pendientes', sa.Column('empresa_id', sa.UUID(), nullable=True))
    op.alter_column('entregas_pendientes', 'usuario_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(op.f('fk_entregas_pendientes_empresa_id_empresas'), 'entregas_pendientes', 'empresas', ['empresa_id'], ['id'])
    op.create_check_constraint(op.f('ck_entregas_pendientes_un_solo_duenio'), 'entregas_pendientes', 'num_nonnulls(empresa_id, usuario_id) = 1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Antes de esto una entrega solo podía ser de un chofer: las de una empresa no tienen a dónde volver.
    de_empresa = op.get_bind().execute(
        sa.text("SELECT count(*) FROM entregas_pendientes WHERE empresa_id IS NOT NULL")
    ).scalar()
    if de_empresa:
        raise RuntimeError(
            f"No se puede volver atrás: hay {de_empresa} entrega(s) reprogramada(s) de una empresa."
        )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_entregas_pendientes_un_solo_duenio'), 'entregas_pendientes', type_='check')
    op.drop_constraint(op.f('fk_entregas_pendientes_empresa_id_empresas'), 'entregas_pendientes', type_='foreignkey')
    op.alter_column('entregas_pendientes', 'usuario_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('entregas_pendientes', 'empresa_id')
    # ### end Alembic commands ###
