"""agrega veces_salteada a paradas_ruta

Revision ID: 74fccceaa900
Revises: 0e909ac798f2
Create Date: 2026-09-30 11:56:10.022864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74fccceaa900'
down_revision: Union[str, Sequence[str], None] = '0e909ac798f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paradas_ruta', sa.Column('veces_salteada', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paradas_ruta', 'veces_salteada')
    # ### end Alembic commands ###
