"""agrega seguimiento de incidencias y entregas pendientes

Revision ID: 7aea858b39c6
Revises: 74fccceaa900
Create Date: 2026-09-30 15:53:55.984203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aea858b39c6'
down_revision: Union[str, Sequence[str], None] = '74fccceaa900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entregas_pendientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('parada_origen_id', sa.UUID(), nullable=False),
    sa.Column('incidencia_id', sa.UUID(), nullable=True),
    sa.Column('carga_kg', sa.Integer(), nullable=False),
    sa.Column('unidades', sa.Integer(), nullable=False),
    sa.Column('ventana_inicio', sa.Integer(), nullable=True),
    sa.Column('ventana_fin', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'INCLUIDA', name='estado_entrega_pendiente', native_enum=False), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_inclusion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ruta_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name=op.f('fk_entregas_pendientes_cliente_id_clientes')),
    sa.ForeignKeyConstraint(['incidencia_id'], ['incidencias.id'], name=op.f('fk_entregas_pendientes_incidencia_id_incidencias')),
    sa.ForeignKeyConstraint(['parada_origen_id'], ['paradas_ruta.id'], name=op.f('fk_entregas_pendientes_parada_origen_id_paradas_ruta')),
    sa.ForeignKeyConstraint(['ruta_id'], ['rutas.id'], name=op.f('fk_entregas_pendientes_ruta_id_rutas')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_entregas_pendientes_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entregas_pendientes')),
    sa.UniqueConstraint('parada_origen_id', name=op.f('uq_entregas_pendientes_parada_origen_id'))
    )
    # Las incidencias que ya existen son historial anterior al seguimiento: se
    # dejan resueltas y cerradas para no inundar "pendientes" de ruido viejo.
    op.add_column('incidencias', sa.Column('estado', sa.Enum('PENDIENTE', 'RESUELTA', name='estado_incidencia', native_enum=False), nullable=False, server_default='RESUELTA'))
    op.add_column('incidencias', sa.Column('resolucion', sa.Enum('REPROGRAMADA', 'CERRADA', name='resolucion_incidencia', native_enum=False), nullable=True))
    op.add_column('incidencias', sa.Column('fecha_resolucion', sa.DateTime(timezone=True), nullable=True))
    op.execute("UPDATE incidencias SET resolucion = 'CERRADA', fecha_resolucion = fecha_hora")
    # A partir de ahora el estado inicial lo decide la aplicación (pendiente).
    op.alter_column('incidencias', 'estado', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidencias', 'fecha_resolucion')
    op.drop_column('incidencias', 'resolucion')
    op.drop_column('incidencias', 'estado')
    op.drop_table('entregas_pendientes')
    # ### end Alembic commands ###
