"""login con google

Revision ID: eb99de48cd4e
Revises: ed15b36969db
Create Date: 2026-10-06 17:20:21.783249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb99de48cd4e'
down_revision: Union[str, Sequence[str], None] = 'ed15b36969db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('google_sub', sa.String(length=255), nullable=True))
    op.alter_column('usuarios', 'contrasena_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_usuarios_google_sub'), 'usuarios', ['google_sub'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Las cuentas creadas con Google no tienen contraseña: no hay hash que restaurar.
    sin_contrasena = op.get_bind().execute(
        sa.text("SELECT count(*) FROM usuarios WHERE contrasena_hash IS NULL")
    ).scalar()
    if sin_contrasena:
        raise RuntimeError(
            f"No se puede volver atrás: hay {sin_contrasena} usuario(s) sin contraseña "
            "(creados con Google)."
        )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_google_sub'), table_name='usuarios')
    op.alter_column('usuarios', 'contrasena_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('usuarios', 'google_sub')
    # ### end Alembic commands ###
