"""agrega nombre a rutas

Revision ID: ed15b36969db
Revises: 7aea858b39c6
Create Date: 2026-09-30 16:33:15.753410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed15b36969db'
down_revision: Union[str, Sequence[str], None] = '7aea858b39c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rutas', sa.Column('nombre', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rutas', 'nombre')
    # ### end Alembic commands ###
